FROM ruby:3.3.4-slim

WORKDIR /rails

ENV RAILS_ENV=development \
    BUNDLE_PATH=/usr/local/bundle \
    BUNDLE_WITHOUT=""

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential \
      libpq-dev \
      curl \
      git \
      nano \
    && rm -rf /var/lib/apt/lists/*

# Install gems — copy manifests first so Docker layer cache is reused
# when only app code changes.
COPY Gemfile ./
RUN bundle install && \
    # Stash the lock file so COPY . . below doesn't destroy it
    cp Gemfile.lock /usr/local/bundle/Gemfile.lock

# Copy application code (may not include Gemfile.lock on the host)
COPY . .

# Restore the lock generated by bundle install (canonical source of truth)
RUN cp /usr/local/bundle/Gemfile.lock Gemfile.lock

EXPOSE 3000

ENTRYPOINT ["bin/docker-entrypoint"]
CMD ["bin/rails", "server", "-b", "0.0.0.0"]
